/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author karlylvg
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuEmpresa = new javax.swing.JMenu();
        jMenuItemEmpresa = new javax.swing.JMenuItem();
        jMenuDepartamento = new javax.swing.JMenu();
        jMenuItemDep = new javax.swing.JMenuItem();
        jMenuEmpleado = new javax.swing.JMenu();
        jMenuItemEmpleado = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mantenimiento Empresa - Departamento - Empleado");

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1077, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jMenuEmpresa.setText("Empresa");

        jMenuItemEmpresa.setText("Agregar/Editar");
        jMenuItemEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEmpresaActionPerformed(evt);
            }
        });
        jMenuEmpresa.add(jMenuItemEmpresa);

        jMenuBar1.add(jMenuEmpresa);

        jMenuDepartamento.setText("Departamento");

        jMenuItemDep.setText("Agregar/Editar");
        jMenuItemDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDepActionPerformed(evt);
            }
        });
        jMenuDepartamento.add(jMenuItemDep);

        jMenuBar1.add(jMenuDepartamento);

        jMenuEmpleado.setText("Empleado");

        jMenuItemEmpleado.setText("Agregar/Editar");
        jMenuItemEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEmpleadoActionPerformed(evt);
            }
        });
        jMenuEmpleado.add(jMenuItemEmpleado);

        jMenuBar1.add(jMenuEmpleado);

        jMenuExit.setText("Salir");
        jMenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuExitMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEmpresaActionPerformed
        var empresaVentana = new EmpresaVista(this.jDesktopPane1);
        this.jDesktopPane1.add(empresaVentana);
        empresaVentana.setIconifiable(true);
        empresaVentana.setClosable(true);
        empresaVentana.setResizable(true);
        empresaVentana.setVisible(true);
    }//GEN-LAST:event_jMenuItemEmpresaActionPerformed

    private void jMenuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuExitMouseClicked
        
        
        int opt = JOptionPane.showConfirmDialog(this, "SEGURO?", "SALIR DEL PROGRAMA",JOptionPane.YES_NO_OPTION );
        if (opt == 0) {
            System.exit(0);
        }
        
        
    }//GEN-LAST:event_jMenuExitMouseClicked

    private void jMenuItemDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDepActionPerformed
        try {
            var departamentoVentana = new DepartamentoVista(this.jDesktopPane1);
            this.jDesktopPane1.add(departamentoVentana);
            departamentoVentana.setIconifiable(true);
            departamentoVentana.setClosable(true);
            departamentoVentana.setResizable(true);
            departamentoVentana.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemDepActionPerformed

    private void jMenuItemEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEmpleadoActionPerformed
        var empleadoVentana = new EmpleadoVista(this.jDesktopPane1);
        this.jDesktopPane1.add(empleadoVentana);
        empleadoVentana.setIconifiable(true);
        empleadoVentana.setClosable(true);
        empleadoVentana.setResizable(true);
        empleadoVentana.setVisible(true);
    }//GEN-LAST:event_jMenuItemEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDepartamento;
    private javax.swing.JMenu jMenuEmpleado;
    private javax.swing.JMenu jMenuEmpresa;
    private javax.swing.JMenu jMenuExit;
    private javax.swing.JMenuItem jMenuItemDep;
    private javax.swing.JMenuItem jMenuItemEmpleado;
    private javax.swing.JMenuItem jMenuItemEmpresa;
    // End of variables declaration//GEN-END:variables
}
